### ISSUE TITLE
Daoファイルを正しく生成できません。

### ISSUE THREAD

**Issue by weiqingfei** [domaframework/doma-gen#37]
EntityのpackageNameを4階層以上指定した場合、生成したDaoクラスには、Entityクラスのimport宣言はなくなります。

例：
task gen << {
    ant.taskdef(resource: 'domagentask.properties',
        classpath: configurations.domaGenRuntime.asPath)
    ant.gen(url: 'jdbc:mysql://localhost:3306/dbname?useUnicode=true&characterEncoding=UTF-8&useSSL=false', user: 'username', password: 'password') {
        entityConfig(packageName: 'jp.co.abc.entity',useListener: false)
        daoConfig(packageName: 'jp.co.abc.dao')
        sqlConfig()
    }
}

**Comment by nakamura-to** [comment]
試してみたのですが、私の環境では再現できませんでした（正常に生成されました）。
生成されたDaoクラスとEntityクラスのソースコードを見せてもらえないでしょうか？
DaoクラスにおけるEntityクラスのimport宣言以外の行を見ることで何かわかるかもしれません。

**Comment by weiqingfei** [comment]
Spring Tool Suiteでプロジェクトを削除して、新規作成しましたら、本現象を解消しました。
環境の問題だと思います。
大変失礼しました。
本issueをcloseします。
