### ISSUE TITLE
EntityクラスのEnum対応についての質問

### ISSUE THREAD

**Issue by hinoko58** [domaframework/doma-gen#46]
作成されるEntityのフィルドはDBの定義により出力されると思いますが、Enumに対応するように出力可能でしょうか？

※後entityConfigにsuperclassNameを指定したらエラーになります。
参考になるページなどあるでしょうか？

```gradle

configurations {
    domaGenRuntime
}
repositories {
    mavenCentral()
    maven {url 'https://oss.sonatype.org/content/repositories/snapshots/'}
}

dependencies {
    domaGenRuntime 'org.seasar.doma:doma-gen:2.18.0'
    domaGenRuntime 'org.mariadb.jdbc:mariadb-java-client:2.1.2'
}


task gen << {
    ant.taskdef(resource: 'domagentask.properties',
            classpath: configurations.domaGenRuntime.asPath)
    ant.gen(url: 'jdbc:mariadb://xxx:3306/test',dialectName:"mysql",driverClassName:"org.mariadb.jdbc.Driver", user: 'test', password: 'test',templatePrimaryDir: "src/domaTemplate") {
        entityConfig(
                 superclassName:'samples.domain.DomaEntity'
                ,packageName:'samples.domain.entity',originalStatesPropertyName:"original",useListener:true
                ,listenerSuperclassName:'samples.domain.entity.DomaEntityListener'
                ,overwrite: true
        )
        daoConfig(packageName:'samples.dao',suffix:"DaoGen" ,overwrite:true)
        sqlConfig()
    }
}
```

**Comment by nakamura-to** [comment]
> Enumに対応するように出力可能でしょうか？

はい、できます。プロパティファイルにエンティティフィールドとEnumクラスのマッピングを記述してください。
http://doma-gen.readthedocs.io/ja/2.18.0/gen/#id6

> ※後entityConfigにsuperclassNameを指定したらエラーになります。

どんなエラーになりますか？想像ですが指定したクラスへのクラスパスが適切でないのかもしれません。ant.taskdefでclasspathを指定する例はGradleのドキュメントが参考になります。

https://docs.gradle.org/4.3/userguide/ant.html#sec:using_custom_ant_tasks

**Comment by hinoko58** [comment]
迅速な解答ありがとう御座います。
Enumに関しては参考のページで解決しました。

後、superclassNameのエラーですが、

想像していただいた通りのエラーです。
以下のエラーメッセージです。

[DOMAGEN0013] プロパティ[superclassName]が表すクラス[samples.domain.entity.DomaEntity]が見つかりません。 ・・・・

上記の例のsamples.domain.entity.DomaEntityは現在開発中のプロジェクト内に存在します。

以下の設定により、listenerは正しく出力されます。
,listenerSuperclassName:'samples.domain.entity.DomaEntityListener'

samples.domain.entity.DomaEntityをライブラリーにして、それをクラスパスに設定する必要があるでしょうか？

**Comment by nakamura-to** [comment]
> samples.domain.entity.DomaEntityをライブラリーにして、それをクラスパスに設定する必要があるでしょうか？

いえ、その必要はありません。 `sourceSets.main.output` をクラスパスに追加すればいいと思います。doma-genのテスト用のプロジェクトでそのようなことをしています。
https://github.com/domaframework/doma-gen-it/blob/2.18.0/build.gradle#L64

**Comment by hinoko58** [comment]
迅速な回答ありがとうございます。
解決できました。
素晴らしい、昨日の提供ありがとうございます。
