### ISSUE TITLE
カラムがnot null かどうか取得したい

### ISSUE THREAD

**Issue by sho-yamashita** [domaframework/doma-gen#51]
一点質問させてください。

domagenで作ったjavaクラスでカラムがNotNullのプロパティに対して、
@NotNullをつけたいと考えています。

そこで質問です。
entity.ftl内でcolumnmetaのnullableの値を参照できれば実現可能と考えているのですが
可能でしょうか。
https://github.com/domaframework/doma-gen/blob/master/src/main/java/org/seasar/doma/extension/gen/ColumnMeta.java

EntityPropertyDescにはColumnMetaの情報を持っていないようだったので
やり方がわからず（そもそもできるのかがわからず）質問させていただいた次第です。
https://github.com/domaframework/doma-gen/blob/master/src/main/java/org/seasar/doma/extension/gen/EntityPropertyDesc.java

**Comment by nakamura-to** [comment]
> entity.ftl内でcolumnmetaのnullableの値を参照できれば実現可能と考えているのですが可能でしょうか。
はい、可能です。

> EntityPropertyDescにはColumnMetaの情報を持っていないようだったので
そうなんです。持っていないですね。

Domaのコードに手を加えずに実現するなら `EntityPropertyDescFactory` と `EntityPropertyDesc` と`GlobalFactory` のサブクラスを作ってもらって、Doma-Genの  `globalFactoryClassName` に指定してもらう方法があります。`ColumnMeta` を持った `EntityPropertyDesc`　を生成されるようにしてもらえれば freemarkerのテンプレートで参照できると思います。

Domaの標準として `ColumnMeta` をentity.ftlから参照できるようにすべきということであればPRいただければ取り込みたいと思います！

**Comment by sho-yamashita** [comment]
ご回答ありがとうございます。

やはり、標準ではできず、アドオンが必要ということですね！
了解しました。
